[versions]
kotlin = "2.4.10"
ktor = "3.2.3"
exposed = "1.0.0-rc-4"
hikari = "5.1.0"
postgresql = "42.7.3"
koin = "3.5.3"
openapi-tools = "5.4.0"
dotenv = "6.5.1"
logback = "1.5.24"
apksig = "8.1.1"
tomlj = "1.1.1"
semver4j = "6.0.0"

[libraries]
# Ktor
ktor-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktor" }
ktor-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktor" }
ktor-call-logging = { module = "io.ktor:ktor-server-call-logging-jvm", version.ref = "ktor" }
ktor-auth = { module = "io.ktor:ktor-server-auth-jvm", version.ref = "ktor" }

# Ktor client
ktor-client-core = { module = "io.ktor:ktor-client-core-jvm", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp-jvm", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation-jvm", version.ref = "ktor" }
ktor-client-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

# Ktor OpenAPI tools
ktor-swagger-ui = { module = "io.github.smiley4:ktor-swagger-ui", version.ref = "openapi-tools" }
ktor-openapi = { module = "io.github.smiley4:ktor-openapi", version.ref = "openapi-tools" }

# Koin
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-logger = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }

# Exposed
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }

# Hikari & Postgres
hikari-cp = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }

# Other
dotenv = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv" }
tomlj = { module = "org.tomlj:tomlj", version.ref = "tomlj" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
apksig = { module = "com.android.tools.build:apksig", version.ref = "apksig" }
semver4j = { module = "org.semver4j:semver4j", version.ref = "semver4j" }

# Kotlin Test
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
patcher-runtimes = { id = "me.brosssh.patcher-runtimes" }
