[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string] $StockApk,

    [Parameter(Mandatory)]
    [string] $PatchedApk,

    [string] $OutputFile = (Join-Path $PSScriptRoot 'artifacts\local\RedFlagDeals-Forums-v1.11.7-revanced-20260821-192035-code.smali.diff'),

    [switch] $Overwrite
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$projectRoot = $PSScriptRoot
$stock = (Resolve-Path -LiteralPath $StockApk).Path
$patched = (Resolve-Path -LiteralPath $PatchedApk).Path
$output = [IO.Path]::GetFullPath($OutputFile)
$apktool = Join-Path $projectRoot '.tools\apktool_3.0.3.jar'
if (-not (Test-Path -LiteralPath $apktool)) {
    throw "Pinned Apktool is missing: $apktool"
}
if ((Test-Path -LiteralPath $output) -and -not $Overwrite) {
    throw "Refusing to overwrite existing diff: $output"
}

$workDirectory = Join-Path $projectRoot ("build\code-diff\" + [guid]::NewGuid().ToString('N'))
$stockDecoded = Join-Path $workDirectory 'stock'
$patchedDecoded = Join-Path $workDirectory 'patched'
New-Item -ItemType Directory -Path $workDirectory -Force | Out-Null
New-Item -ItemType Directory -Path (Split-Path -Parent $output) -Force | Out-Null

function Decode-Apk([string] $Apk, [string] $Destination) {
    $decodeLog = (& java -jar $apktool d -f $Apk -o $Destination 2>&1 | Out-String)
    if ($LASTEXITCODE -ne 0) {
        throw "Apktool could not decode $Apk`n$decodeLog"
    }
}

function Get-TargetSmaliMap([string] $Root, [string[]] $Targets) {
    $map = @{}
    $allSmali = @(Get-ChildItem -LiteralPath $Root -Recurse -File -Filter '*.smali')
    foreach ($target in $Targets) {
        $matches = @($allSmali | Where-Object {
            ($_.FullName -replace '\\', '/') -like "*/$target"
        })
        if ($matches.Count -gt 1) {
            throw "Expected at most one decoded class matching $target, found $($matches.Count)."
        }
        if ($matches.Count -eq 1) {
            $map[$target] = $matches[0].FullName
        }
    }
    return $map
}

Decode-Apk $stock $stockDecoded
Decode-Apk $patched $patchedDecoded
$targets = @(
    'com/ypg/rfdapilib/api/adapter/YidAdapter.smali',
    'com/ypg/rfdapilib/api/adapter/YidAdapter$1.smali',
    'com/ypg/rfdapilib/auth/YidAccountManager.smali',
    'com/ypg/rfdforums/sections/topic/TopicFragment.smali',
    'com/ypg/rfdforums/sections/topic/TopicFragment$onRefresh$1.smali',
    'com/ypg/rfdforums/sections/topics/TopicListAdapter.smali',
    'app/revanced/extension/redflagdeals/Diagnostics.smali'
)
$stockMap = Get-TargetSmaliMap $stockDecoded $targets
$patchedMap = Get-TargetSmaliMap $patchedDecoded $targets
$relativePaths = @($targets | Where-Object { $stockMap.ContainsKey($_) -or $patchedMap.ContainsKey($_) })

$sections = [System.Collections.Generic.List[string]]::new()
$changedFiles = 0
foreach ($relative in $relativePaths) {
    $stockPath = $stockMap[$relative]
    $patchedPath = $patchedMap[$relative]
    $same = $stockPath -and $patchedPath -and
        ((Get-FileHash -LiteralPath $stockPath -Algorithm SHA256).Hash -eq (Get-FileHash -LiteralPath $patchedPath -Algorithm SHA256).Hash)
    if ($same) {
        continue
    }
    $changedFiles++
    $section = (& git diff --no-index --no-ext-diff --minimal --src-prefix='a/' --dst-prefix='b/' -- `
        $(if ($stockPath) { $stockPath } else { '/dev/null' }) `
        $(if ($patchedPath) { $patchedPath } else { '/dev/null' }) 2>&1 | Out-String)
    if ($LASTEXITCODE -ne 0 -and $LASTEXITCODE -ne 1) {
        throw "git diff failed for $relative"
    }
    $section = (($section -split "`r?`n") | ForEach-Object {
        if ($_ -match '^diff --git ') {
            "diff --git a/$relative b/$relative"
        } elseif ($_ -match '^--- ' -and $_ -notmatch '/dev/null$') {
            "--- a/$relative"
        } elseif ($_ -match '^\+\+\+ ' -and $_ -notmatch '/dev/null$') {
            "+++ b/$relative"
        } else {
            $_
        }
    }) -join "`n"
    $sections.Add($section.TrimEnd())
}

$stockHash = (Get-FileHash -LiteralPath $stock -Algorithm SHA256).Hash.ToLowerInvariant()
$patchedHash = (Get-FileHash -LiteralPath $patched -Algorithm SHA256).Hash.ToLowerInvariant()
$header = @"
# Executable-code diff: stock vs Stage 2 ReVanced APK

This file is generated by generate-code-diff.ps1 with pinned Apktool 3.0.3.
It contains every Dalvik .smali class targeted by this patch, excluding ZIP
metadata, resources, signatures, and other packaging noise. Unchanged targeted
classes are omitted.

- Stock APK SHA-256: $stockHash
- Patched APK SHA-256: $patchedHash
- Changed .smali files: $changedFiles

"@
$header += '```diff' + "`n"
$footer = "`n" + '```' + "`n"
Set-Content -LiteralPath $output -Value ($header + ($sections -join "`n`n") + $footer) -Encoding utf8NoBOM
Write-Host "Created $output with $changedFiles changed .smali files."
