name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  release:
    name: Release
    permissions:
      contents: write
      issues: write
      packages: write
    runs-on: ubuntu-latest
    env:
      GPR_USER: ${{ github.actor }}
      GPR_KEY: ${{ secrets.GPR_KEY }}
      ORG_GRADLE_PROJECT_githubPackagesUsername: ${{ github.actor }}
      ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ secrets.GPR_KEY }}
      ORG_GRADLE_PROJECT_signingRequired: "false"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v2

      - name: Build
        run: ./gradlew build

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: 'npm'

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm exec semantic-release
