package app.arsound.patches.soundcloud.misc.branding

import app.revanced.patcher.patch.resourcePatch
import app.arsound.util.ResourceGroup
import app.arsound.util.asSequence
import app.arsound.util.copyResources
import org.w3c.dom.Element

private const val SPLASH_FRAMES = 25
private val DENSITIES = listOf("mdpi", "hdpi", "xhdpi", "xxhdpi", "xxxhdpi")
private val ARTWORK_PLACEHOLDER_NAMES = listOf("ic_default_playable_artwork_placeholder", "ic_default_playable_artwork_placeholder_dark")
private val LOGO_NAMES = listOf("ic_logo_cloud", "ic_logo_cloud_active", "ic_logo_cloud_dark", "ic_logo_cloud_light", "ic_logo_cloud_launcher")
private val LAUNCHER_FOREGROUND_NAMES = listOf(
    "ic_launcher_foreground", "ic_launcher_foreground_black", "ic_launcher_foreground_orange", "ic_launcher_foreground_white",
)

/**
 * Resources are generated by tools/branding/generate.py from the exported icon set.
 */
/** Arsound branding: Replaces the launcher icon, the start animation and the SoundCloud logo icons with the Arsound icon. Part of the "Arsound" patch, not shown on its own. */
val brandingPatch = resourcePatch {
    compatibleWith("com.soundcloud.android")

    apply {
        copyResources(
            "soundcloud/branding",
            ResourceGroup("drawable-nodpi", "arsound_launcher_foreground.png"),
            ResourceGroup("drawable-nodpi", *Array(SPLASH_FRAMES) { "arsound_splash_%02d.png".format(it) }),
            ResourceGroup("drawable", "arsound_splash.xml"),
            *listOf("mdpi", "hdpi", "xhdpi", "xxhdpi", "xxxhdpi")
                .map { ResourceGroup("drawable-$it", "arsound_icon.png") }
                .toTypedArray(),
        )

        val res = get("res")
        // The decoded night variant may be named raw-night-v8; keep a single night file.
        res.listFiles { file -> file.isDirectory && file.name.startsWith("raw-night") && file.name != "raw-night" }!!
            .forEach { it.resolve("loading_animation.json").delete() }

        // Every launcher icon, including the alternative app icons users can pick in SoundCloud.
        res.listFiles { file -> file.isDirectory && file.name.startsWith("mipmap-anydpi") }!!
            .flatMap { directory -> directory.listFiles { file -> file.name.startsWith("ic_launcher") }!!.toList() }
            .forEach { icon ->
                icon.writeText(
                    """
                    <?xml version="1.0" encoding="utf-8"?>
                    <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
                        <background android:drawable="@android:color/black" />
                        <foreground android:drawable="@drawable/arsound_launcher_foreground" />
                        <monochrome android:drawable="@drawable/arsound_launcher_foreground" />
                    </adaptive-icon>
                    """.trimIndent(),
                )
            }

        // SoundCloud logo spots: its vectors in every density folder are removed and replaced by letter vectors
        // with the same names, sizes and colours, so the 88dp logo on the sign-in screen stays sharp.
        // The launcher foregrounds become PNGs, because Compose screens cannot draw bitmap XML.
        res.listFiles { file -> file.isDirectory && file.name.startsWith("drawable") }!!
            .flatMap { directory ->
                directory.listFiles { file ->
                    file.name.endsWith(".xml") && file.nameWithoutExtension in LOGO_NAMES + LAUNCHER_FOREGROUND_NAMES
                }!!.toList()
            }
            .forEach { it.delete() }

        // Track artwork placeholder: bitmaps instead of vectors, see tools/branding/generate.py.
        res.listFiles { file -> file.isDirectory && file.name.startsWith("drawable") }!!
            .flatMap { directory ->
                directory.listFiles { file ->
                    file.name.endsWith(".xml") && file.nameWithoutExtension in ARTWORK_PLACEHOLDER_NAMES
                }!!.toList()
            }
            .forEach { it.delete() }
        copyResources(
            "soundcloud/branding",
            ResourceGroup("drawable", *LOGO_NAMES.map { "$it.xml" }.toTypedArray()),
            ResourceGroup("drawable-nodpi", *ARTWORK_PLACEHOLDER_NAMES.map { "$it.png" }.toTypedArray()),
            ResourceGroup("drawable-night-nodpi", "ic_default_playable_artwork_placeholder.png"),
            ResourceGroup("drawable-nodpi", *LAUNCHER_FOREGROUND_NAMES.map { "$it.png" }.toTypedArray()),
            // The loading animation of the whole app (Lottie): the letter being drawn instead of the cloud.
            ResourceGroup("raw", "loading_animation.json"),
            ResourceGroup("raw-night", "loading_animation.json"),
        )

        // The start screen shows the drawing animation of the letter instead of the orange cloud.
        res.listFiles { file -> file.isDirectory && file.name.startsWith("values") }!!
            .filter { it.resolve("styles.xml").exists() }
            .forEach { directory ->
                document("res/${directory.name}/styles.xml").use { document ->
                    document.getElementsByTagName("item").asSequence().map { it as Element }.forEach { item ->
                        when (item.getAttribute("name")) {
                            "windowSplashScreenAnimatedIcon", "android:windowSplashScreenAnimatedIcon" ->
                                if (item.textContent.startsWith("@drawable/ic_launcher_foreground")) {
                                    item.textContent = "@drawable/arsound_splash"
                                }
                            "windowSplashScreenAnimationDuration" ->
                                if (item.textContent == "0") item.textContent = "1000"
                        }
                    }
                }
            }
    }
}
